### ISSUE TITLE
Автоматическое добавление кармы Маше

### ISSUE THREAD

**Issue by AZatsepa** [TheBlackArroVV/super_karma_bot#14]
Добавлять карму Маше при попадании в чат сообщения от неё

**Comment by yashka713** [comment]
@MariiaAlehina
Как тебе идея?

**Comment by MariiaAlehina** [comment]
я за справедливость) поэтому неть

**Comment by yashka713** [comment]
Закрыто до прихода новой Маши в отдел.

**Comment by AZatsepa** [comment]
Это было бы справедливым потому что 
1) Маша - девушка
2) Машу не лайкают, она сама это говорила

Считаю, что процесс нужно автоматизировать.

**Comment by yashka713** [comment]
@AZatsepa 

> Маша - девушка

Я считаю несправедливыми поблажки, по половому признаку.

> Машу не лайкают, она сама это говорила

![Знімок екрану з 2019-07-19 14-31-02](https://user-images.githubusercontent.com/15985355/61532287-07f38f80-aa32-11e9-9b80-65417ce36f22.png)

Все у нее в порядке
:wink:
